version: '3.2'

services:
  db:
    restart: "no"

  adminer:
    image: dockette/adminer:mysql
    restart: "no"
    environment:
      MEMORY: 512M
      UPLOAD: 4096M
    ports:
      - 8088:80

  as:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
#    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails db:setup && rails s -p 3000 -b '0.0.0.0'"
    restart: "no"
    volumes:
      - .:/bilancio
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000

  pe:
    build: .
    command: /bin/sh -c "prometheus_exporter"
    restart: "no"
    volumes:
      - .:/bilancio
    environment:
      RAILS_ENV: development
    ports:
      - 9394:9394

volumes:
  bilancio:
