
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bilancio_development
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build: .
    volumes:
      - .:/bilancio
      - node_modules:/bilancio/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
    depends_on:
      - db

volumes:
  mysql_data:
  node_modules:
