version: '3.2'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  as:
    env_file:
      - .env
    links:
      - db

  pe:
    env_file:
      - .env
    links:
      - as

volumes:
  mysql:
