production:
  represent_boolean_as_integer: false
  token_key_base: <%= ENV["TOKEN_KEY_BASE"] %>
  authelia_enabled: <%= ENV.fetch("AUTHELIA_ENABLED", "false") == "true" %>
  authelia_secret: <%= ENV["AUTHELIA_SECRET"] %>
test:
  represent_boolean_as_integer: true
  token_key_base: <%= ENV.fetch("TOKEN_KEY_BASE", "insecure-dev-test-token-key") %>
  authelia_enabled: true
  authelia_secret: test-authelia-secret
development:
  represent_boolean_as_integer: true
  token_key_base: <%= ENV.fetch("TOKEN_KEY_BASE", "insecure-dev-test-token-key") %>
  authelia_enabled: <%= ENV.fetch("AUTHELIA_ENABLED", "false") == "true" %>
  authelia_secret: <%= ENV.fetch("AUTHELIA_SECRET", "") %>
