production:
  represent_boolean_as_integer: false
  token_key_base: <%= ENV["TOKEN_KEY_BASE"] %>
test:
  represent_boolean_as_integer: true
  token_key_base: <%= ENV.fetch("TOKEN_KEY_BASE", "insecure-dev-test-token-key") %>
development:
  represent_boolean_as_integer: true
  token_key_base: <%= ENV.fetch("TOKEN_KEY_BASE", "insecure-dev-test-token-key") %>
